version: '3.6'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  web:
    build:
      context: .
    restart: always
    depends_on:
      - db
    environment:
      MIX_ENV: dev
      DATABASE_URL: ecto://postgres:postgres@db/url_shortener_dev
    env_file:
      - .env
    ports:
      - '4000:4000'

volumes:
  pgdata:
